# Generated by Django 5.0.6 on 2024-05-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('school', '0004_alter_classroom_classroom_tyoe_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=70, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professore(a)s',
            },
        ),
        migrations.CreateModel(
            name='PhoneTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(verbose_name='Código do Pais')),
                ('locale_code', models.IntegerField(verbose_name='Código da Localidade')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('phone_type', models.CharField(choices=[('C', 'Celular'), ('P', 'Principal'), ('W', 'Whatsapp'), ('T', 'Telegran'), ('O', 'Outro')], default='P', max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Telefone do Professor(a)',
                'verbose_name_plural': 'Telefones do Professor(a)',
            },
        ),
        migrations.CreateModel(
            name='AddressTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('zipcode', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='CEP')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Endereço do Professor(a)',
                'verbose_name_plural': 'Endereços do Professor(a)',
            },
        ),
    ]
