# Generated by Django 5.0.6 on 2024-05-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Professor(a)', 'verbose_name_plural': 'Professores'},
        ),
    ]
