# Generated by Django 5.0.3 on 2024-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('pode_mudar_status', 'pode_mudar status'), ('pode_fazer_outra_coisa', 'Pode fazer outra coisa')), 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
