# Generated by Django 5.0.3 on 2024-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
