# Generated by Django 5.0.6 on 2024-05-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Tipo de Endereço')),
            ],
            options={
                'verbose_name': 'Tipo de Endereço',
                'verbose_name_plural': 'Tipos de Endereço',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Cidade')),
                ('ibge_number', models.CharField(max_length=10, verbose_name='Código do IBGE')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Estado')),
                ('acronym', models.CharField(max_length=2, verbose_name='Sigla do Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8, unique=True, verbose_name='CEP')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('district', models.CharField(max_length=40, verbose_name='Bairro')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.addresstype', verbose_name='Tipo de Lougradouro')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state', verbose_name='Estado'),
        ),
    ]
