<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-09 14:33

import django.db.models.deletion
=======
# Generated by Django 5.0.3 on 2024-04-18 12:43

import django.db.models.deletion
from django.conf import settings
>>>>>>> 70b58ba (add app school and config pages)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('core', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 70b58ba (add app school and config pages)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('fantasy_name', models.CharField(max_length=30, verbose_name='Apelido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='PhoneSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(verbose_name='Código do Pais')),
                ('locale_code', models.IntegerField(verbose_name='Código da Localidade')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('phone_type', models.CharField(choices=[('C', 'Celular'), ('P', 'Principal'), ('W', 'Whatsapp'), ('T', 'Telegran'), ('O', 'Outro')], default='P', max_length=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'Telefone da Escola',
                'verbose_name_plural': 'Telefones da Escola',
            },
        ),
        migrations.CreateModel(
            name='AddressSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Endereço')),
                ('scholl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Endereço da Escola',
                'verbose_name_plural': 'Endereços da Escola',
=======
            name='StructSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estrutura')),
                ('struct_type', models.CharField(choices=[('SLAU', 'Sala de Aula'), ('QPE', 'Quadra Poliesportiva'), ('ESPR', 'Espaço de Recreação'), ('SLIN', 'Sala de Informatica/Computação'), ('LAB', 'Laboratório'), ('PROF', 'Sala dos Professores')], max_length=4, verbose_name='Tipo de estrutura')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura (m)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura (m)')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Comprimento (m)')),
                ('area', models.IntegerField(verbose_name='Area (m2)')),
                ('perimeter', models.IntegerField(verbose_name='Perímetro (m2)')),
                ('vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
            ],
            options={
                'verbose_name': 'StructSchool',
                'verbose_name_plural': 'StructSchools',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Escola')),
                ('cnpj_number', models.CharField(max_length=18, verbose_name='CNPJ da Escola')),
                ('school_number', models.CharField(max_length=20, verbose_name='Numero Cadastro Secretaria')),
                ('address_zipcode', models.CharField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=5, verbose_name='Número')),
                ('address_complement', models.CharField(max_length=20, verbose_name='Complemento')),
                ('address_district', models.CharField(max_length=50, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=70, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='UF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_ddd', models.CharField(max_length=4, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escola',
>>>>>>> 70b58ba (add app school and config pages)
            },
        ),
    ]
