# Generated by Django 5.0.6 on 2024-05-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('fantasy_name', models.CharField(max_length=30, verbose_name='Apelido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='PhoneSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(verbose_name='Código do Pais')),
                ('locale_code', models.IntegerField(verbose_name='Código da Localidade')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('phone_type', models.CharField(choices=[('C', 'Celular'), ('P', 'Principal'), ('W', 'Whatsapp'), ('T', 'Telegran'), ('O', 'Outro')], default='P', max_length=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'Telefone da Escola',
                'verbose_name_plural': 'Telefones da Escola',
            },
        ),
        migrations.CreateModel(
            name='AddressSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Endereço')),
                ('scholl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Endereço da Escola',
                'verbose_name_plural': 'Endereços da Escola',
            },
        ),
    ]
