# Generated by Django 5.0.6 on 2024-05-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressschool',
            old_name='scholl',
            new_name='school',
        ),
    ]
