# Generated by Django 5.0.3 on 2024-04-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructSchool',
        ),
    ]
