# Generated by Django 5.0.3 on 2024-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_fantasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structschool',
            name='area',
            field=models.IntegerField(verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='structschool',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Identificação'),
        ),
        migrations.AlterField(
            model_name='structschool',
            name='perimeter',
            field=models.IntegerField(verbose_name='Perímetro (m)'),
        ),
        migrations.AlterField(
            model_name='structschool',
            name='struct_type',
            field=models.CharField(choices=[('SLAU', 'Sala de Aula'), ('QPE', 'Quadra Poliesportiva'), ('ESPR', 'Espaço de Recreação'), ('SLIN', 'Sala de Informatica/Computação'), ('LAB', 'Laboratório'), ('PROF', 'Sala dos Professores')], max_length=4, verbose_name='Estrutura'),
        ),
    ]
