# Generated by Django 5.0.3 on 2024-04-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_delete_structschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estrutura')),
                ('struct_type', models.CharField(choices=[('SLAU', 'Sala de Aula'), ('QPE', 'Quadra Poliesportiva'), ('ESPR', 'Espaço de Recreação'), ('SLIN', 'Sala de Informatica/Computação'), ('LAB', 'Laboratório'), ('PROF', 'Sala dos Professores')], max_length=4, verbose_name='Tipo de estrutura')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura (m)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura (m)')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Comprimento (m)')),
                ('area', models.IntegerField(verbose_name='Area (m2)')),
                ('perimeter', models.IntegerField(verbose_name='Perímetro (m2)')),
                ('vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'StructSchool',
                'verbose_name_plural': 'StructSchools',
            },
        ),
    ]
