# Generated by Django 5.0.6 on 2024-05-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_scholl_addressschool_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=5, verbose_name='Identificação')),
                ('vacation', models.PositiveIntegerField(verbose_name='Vagas')),
                ('classroom_tyoe', models.CharField(choices=[('P', 'Padrão'), ('E', 'Especial'), ('I', 'Inclusiva'), ('L', 'Laboratório'), ('O', 'Outra')], max_length=1, verbose_name='Tipo de Classe de Aula')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Sala de Aula',
                'verbose_name_plural': 'Salas de Aula',
            },
        ),
        migrations.CreateModel(
            name='TurnSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome do Turno')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Turno Escolar',
                'verbose_name_plural': 'Turnos da Escola',
            },
        ),
    ]
