# Generated by Django 5.0.6 on 2024-05-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classroom_turnschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_tyoe',
            field=models.CharField(choices=[('P', 'Padrão'), ('E', 'Especial'), ('N', 'Informática'), ('L', 'Laboratório'), ('I', 'Inclusiva'), ('O', 'Outra')], max_length=1, verbose_name='Tipo de Classe de Aula'),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data do Inicio')),
                ('end_date', models.DateField(verbose_name='Data do Termino')),
                ('start_recess', models.DateField(verbose_name='Inicio das Férias')),
                ('end_recess', models.DateField(verbose_name='Final das Férias')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
            },
        ),
    ]
