# Generated by Django 5.0.6 on 2024-05-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classroom_classroom_tyoe_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
            },
        ),
        migrations.CreateModel(
            name='HalfyearSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halfyear', models.CharField(choices=[('1S', '1º Semestre'), ('2S', '2º Semestre')], max_length=2, verbose_name='Semestre')),
                ('start', models.DateField(verbose_name='Inicio')),
                ('end', models.DateField(verbose_name='Fim')),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'PeriodAcademicYear',
                'verbose_name_plural': 'PeriodAcademicYears',
            },
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
