# Generated by Django 5.0.6 on 2024-05-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_schoolyear_halfyearschoolyear_delete_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='school',
        ),
        migrations.DeleteModel(
            name='HalfyearSchoolYear',
        ),
        migrations.DeleteModel(
            name='SchoolYear',
        ),
    ]
