# Generated by Django 5.0.6 on 2024-05-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_schoolyear_school_delete_halfyearschoolyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_start', models.DateField(verbose_name='Inicio ano letivo')),
                ('halfyear_start', models.DateField(verbose_name='Inicio Ferias')),
                ('second_start', models.DateField(verbose_name='Inicio 2º Semestre')),
                ('end', models.DateField(verbose_name='Termino ano letivo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
            },
        ),
    ]
