<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-10 22:55

import django.db.models.deletion
=======
# Generated by Django 5.0.3 on 2024-04-22 16:49
=======
# Generated by Django 5.0.3 on 2024-04-26 00:04
>>>>>>> 51a4ac5 (corrections all apps)

import django.db.models.deletion
from django.conf import settings
>>>>>>> 93b9589 (add and config new app group)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('graduation', '0002_alter_discipline_disciplines'),
        ('school', '0004_alter_classroom_classroom_tyoe_academicyear'),
=======
        ('school', '0003_structschool'),
        ('student', '0001_initial'),
        ('teacher', '0003_alter_teacher_options'),
=======
        ('discipline', '0001_initial'),
        ('school', '0001_initial'),
        ('student', '__first__'),
        ('teacher', '__first__'),
>>>>>>> 51a4ac5 (corrections all apps)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 93b9589 (add and config new app group)
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('identification', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=1, verbose_name='Identificador')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='Ano Letivo')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom', verbose_name='Sala de Aula')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.graduation', verbose_name='Graduação')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turnschool', verbose_name='Turno')),
=======
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('identification_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O')], max_length=1, verbose_name='Nome')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.graduation', verbose_name='Graduação')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.structschool', verbose_name='Localização')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escola')),
                ('students', models.ManyToManyField(to='student.student', verbose_name='Estudantes')),
                ('teacher_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Professor Responável')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
>>>>>>> 93b9589 (add and config new app group)
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
