# Generated by Django 5.0.3 on 2024-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='turn',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, null=True, verbose_name='Turno'),
        ),
    ]
