# Generated by Django 5.0.6 on 2024-05-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_daygridgroup_gridgroup_hourgridgroup_weekgridgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourgridgroup',
            name='day',
        ),
        migrations.RemoveField(
            model_name='gridgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='weekgridgroup',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='group',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='group',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='group',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='hourgridgroup',
            name='dicipline',
        ),
        migrations.RemoveField(
            model_name='hourgridgroup',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='DayGridGroup',
        ),
        migrations.DeleteModel(
            name='GridGroup',
        ),
        migrations.DeleteModel(
            name='WeekGridGroup',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='HourGridGroup',
        ),
    ]
