# Generated by Django 5.0.6 on 2024-05-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayGridGroup',
        ),
        migrations.DeleteModel(
            name='WeekGripGroup',
        ),
    ]
