# Generated by Django 5.0.6 on 2024-05-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0005_delete_daygridgroup_delete_weekgripgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekGridGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayweek', models.CharField(choices=[('dom', 'Domingo'), ('seg', 'Sengunda-Feira'), ('ter', 'Terça-Feira'), ('qua', 'Quarta-Feira'), ('qui', 'Sexta-Feira'), ('sex', 'Sexta-Feira'), ('sab', 'Sabado')], max_length=3, verbose_name='Dia da Semana')),
                ('is_lesson', models.BooleanField(verbose_name='Tem Aula?')),
            ],
            options={
                'verbose_name': 'GripGroup',
                'verbose_name_plural': 'GripGroups',
            },
        ),
        migrations.CreateModel(
            name='DayGridGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Horario inicial')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Informe um intervalo em minutos', verbose_name='Duração (minutos)')),
                ('number_classes', models.PositiveIntegerField(default=5, help_text='Informe de aulas no dia', verbose_name='Quantidade de Aulas')),
                ('interval_start', models.DateTimeField(verbose_name='Inicio do Intervalo')),
                ('duration_interval', models.PositiveIntegerField(default=30, help_text='Informe um intervalo em minutos', verbose_name='Duração do intervalo')),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.weekgridgroup', verbose_name='Dia da Semana')),
            ],
            options={
                'verbose_name': 'DayGridGroup',
                'verbose_name_plural': 'DayGridGroups',
            },
        ),
    ]
