# Generated by Django 5.0.6 on 2024-05-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayGridGroup',
        ),
        migrations.DeleteModel(
            name='WeekGridGroup',
        ),
    ]
