# Generated by Django 5.0.6 on 2024-05-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduation', '0002_alter_discipline_disciplines'),
        ('group', '0007_delete_daygridgroup_delete_weekgridgroup'),
        ('school', '0007_schoolyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Horario inicial')),
                ('duration_lesson', models.PositiveIntegerField(default=60, help_text='Informe um intervalo em minutos', verbose_name='Duração (minutos)')),
                ('number_classes', models.PositiveIntegerField(default=5, help_text='Informe de aulas no dia', verbose_name='Quantidade de Aulas')),
                ('interval_start', models.DateTimeField(verbose_name='Inicio do Intervalo')),
                ('duration_interval', models.PositiveIntegerField(default=30, help_text='Informe um intervalo em minutos', verbose_name='Duração do intervalo')),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'GripGroup',
                'verbose_name_plural': 'GripGroups',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=1, verbose_name='Identificador')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom', verbose_name='Sala de Aula')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.graduation', verbose_name='Graduação')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Ano Letivo')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turnschool', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
