# Generated by Django 5.0.6 on 2024-05-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GridGroup',
        ),
    ]
