# Generated by Django 5.0.6 on 2024-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_gridgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridgroup',
            name='interval_start',
            field=models.TimeField(verbose_name='Inicio do Intervalo'),
        ),
    ]
