# Generated by Django 5.0.6 on 2024-05-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_gridgroup_interval_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridgroup',
            name='weekday',
            field=models.CharField(blank=True, choices=[('tuesday', 'tuesday'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Sexta-Feira'), ('Sexta-Feira', 'Sexta-Feira')], max_length=50, null=True, verbose_name='Weekday'),
        ),
    ]
