# Generated by Django 5.0.6 on 2024-05-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_gridgroup_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='identification',
            new_name='group_id',
        ),
        migrations.DeleteModel(
            name='GridGroup',
        ),
    ]
