# Generated by Django 5.0.6 on 2024-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_gridgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridgroup',
            name='dicipline',
            field=models.CharField(blank=True, choices=[('math', 'Matemática'), ('history', 'História'), ('geography', 'Geografia'), ('science', 'Ciência'), ('art', 'Artes'), ('english', 'Inglês'), ('spanish', 'Espanhol'), ('french', 'Francês'), ('dramatics', 'Dramartugia'), ('physicaleducation', 'Educação Física'), ('woodshop', 'Marcenaria'), ('health', 'Saúde'), ('economics', 'Econômia')], max_length=20, null=True, verbose_name='Diciplina'),
        ),
    ]
