# Generated by Django 5.0.6 on 2024-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_gridgroup_dicipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='interval_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração do Intervalo'),
        ),
        migrations.AddField(
            model_name='group',
            name='interval_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio do intervalo'),
        ),
        migrations.AlterField(
            model_name='gridgroup',
            name='day_week',
            field=models.CharField(choices=[('sunday', 'Domingo'), ('monday', 'Segunda-Feira'), ('tuesday', 'Terca-Feira'), ('wednesday', 'Quarta-Feira'), ('thursday', 'Quinta-Feira'), ('friday', 'Sexta-Feira'), ('saturday', 'Sábado')], max_length=15, verbose_name='Dia da Semana'),
        ),
    ]
