# Generated by Django 5.0.6 on 2024-05-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_group_interval_duration_group_interval_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridgroup',
            old_name='grup',
            new_name='group',
        ),
    ]
