# Generated by Django 5.0.6 on 2024-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_rename_grup_gridgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='interval_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração do Intervalo'),
        ),
    ]
