# Generated by Django 5.0.3 on 2024-04-14 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'TypeNotation',
                'verbose_name_plural': 'TypeNotations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Data | Hora Inicio')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Data | Hora Termino')),
                ('type', models.CharField(max_length=1, verbose_name='Tipo de Evento')),
                ('name', models.CharField(max_length=255, verbose_name='Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_finish', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
