# Generated by Django 5.0.6 on 2024-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Compromisso')),
                ('start', models.DateTimeField(help_text='Data DD/MM/AAAA e Hora HH:MM', verbose_name='Inicia em')),
                ('end', models.DateTimeField(blank=True, help_text='Data DD/MM/AAAA e Hora HH:MM', null=True, verbose_name='Termina em')),
                ('all_day', models.BooleanField(default=False, verbose_name='Dia Inteiro?')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start'],
            },
        ),
    ]
