# Generated by Django 5.0.3 on 2024-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Data DD/MM/AAAA e Hora HH:MM', null=True, verbose_name='Termina em'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(help_text='Data DD/MM/AAAA e Hora HH:MM', verbose_name='Inicia em'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Compromisso'),
        ),
    ]
