# Generated by Django 5.0.3 on 2024-04-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_calendarevent_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeNotation',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
