# Generated by Django 5.0.3 on 2024-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_event_user_delete_typenotation_delete_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Será o Dia Inteiro?'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termina em'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(verbose_name='Inicia em'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo do Evento'),
        ),
    ]
