# Generated by Django 5.0.3 on 2024-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Dia Inteiro?'),
        ),
    ]
