# Generated by Django 5.0.3 on 2024-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Matriculado'),
        ),
    ]
