# Generated by Django 5.0.3 on 2024-04-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNoResgistred',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('student.student',),
        ),
        migrations.CreateModel(
            name='StudentResgistred',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('student.student',),
        ),
    ]
