# Generated by Django 5.0.6 on 2024-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='disciplines',
            field=models.ManyToManyField(blank=True, null=True, to='graduation.discipline', verbose_name='Disciplina'),
        ),
    ]
